### ISSUE TITLE
Add documentation for AutocompletePanel

### ISSUE THREAD

**Issue by emilyhorsman** [emilyhorsman/wagtail-autocomplete#8]
- [x] Basic `AutocompletePanel` usage
- [x] Transition from `PageChooserPanel` or `SnippetChooserPanel`
- [x] `ClusterableModel` example
- [x] Clearer explanation of single vs multi usage
- [ ] Public API 
- [x] Add some illustrative gifs of it in action
- [x] Custom properties on models: `autocomplete_create` and `autocomplete_label`

**Comment by tonatos** [comment]
We are waiting for documentation! thank you!

**Comment by emilyhorsman** [comment]
@tonatos You can check out the `docs` branch for somewhat complete documentation: https://github.com/littleweaver/wagtail-autocomplete/tree/4b90efdfa8d22011ef67efecf53ba85815d11bfa/docs

**Comment by tonatos** [comment]
I am very grateful!

**Comment by harrislapiroff** [comment]
I don't remember at all what the Public API checkbox refers to and it's the only thing that's unchecked so I'm gonna go ahead and close this ticket.
